{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosarm64-0.3.0-rc05.klib",
          "size": 202505,
          "sha512": "fc49ac8a24d56af65e83030989880301be76af1e1e24a478634cc540f1791d0f49e6ce2540e1a45e62748522eb58f616e7745042b44a21f9b3ccc5e1ddbf9386",
          "sha256": "9ac8954cd31f0f3c1c2a1ad1287f890902ef34056a9218ea5f2f27aaf073943e",
          "sha1": "8c4f307b66d0eeae5873993993e71f7dc6828e6c",
          "md5": "b76f1e1281a81284c80a48bc437944d1"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosarm64-0.3.0-rc05-metadata.jar",
          "url": "kmock-tvosarm64-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "57a3930ed950fc7ffa0a872471c2af5fbe2a1e487531373c7a26f2006d02bcd4ca83c8060ce2fec18c8cba03ca00b8e792183161d83ee7bf6fd0c8184f84aa33",
          "sha256": "c2564005d8178d22bdf205bff7a7e080c30d33e6eba37cc16ae46da46377ee16",
          "sha1": "ccdb95812fb9b8f3f451204dd1f2c0485e3c2474",
          "md5": "acbb63f79ac56cc7009bb49c42672cc4"
        }
      ]
    }
  ]
}
