{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0/core-0.2.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.2.0.klib",
          "size": 50749,
          "sha512": "b6c87d885310c55aecf32e2b2523710b73d868c842c32165d03196225525c24473759907f1b75bbd1c8a26e1d6f7895d5fc10281cdf787d664c40a7b7a662266",
          "sha256": "22b949d8657ed3d352f4c512a78dd8a365a024e086fd7ee8db667d2712185ead",
          "sha1": "78b3f496557896257769c6950202f544d7cacb6a",
          "md5": "8674330658d2b59111ebd3134c0a80a1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.2.0-metadata.jar",
          "url": "core-iosarm64-0.2.0-metadata.jar",
          "size": 261,
          "sha512": "acd28c4ae59b1337b881e383eaee18ae1a92bf0129d4afed2d3bbbb29eee235cac3fad74dbc76f6b7ce6556b3561d7aa8177d70298aa599b7d419284c636d2c1",
          "sha256": "173e1224298360c9f27f149d4284d3f4174d931fb028a6cb09f2ccc3b39659d6",
          "sha1": "af63d9f1d5b0b606ecb3a0d4af4a7cc601f2c0b7",
          "md5": "f359dd589606e2541cd35f420c6e7ef9"
        }
      ]
    }
  ]
}
