{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0/core-0.2.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0.klib",
          "url": "core-js-0.2.0.klib",
          "size": 61766,
          "sha512": "d22918ed86bed2c66f477298cf823817b04717dd4a3c49d5b6d98a4e495bedf62915dd805141c3f1cd192bce1ec093dec270eaf15c2b063e6950a9844a9a33b5",
          "sha256": "cc9fac0e8962d5bbe8e67ca984f0aab77941f0cae7c15e473641645503324a2a",
          "sha1": "3d6068dcd6d46b6d868d859344dcd6ddfcbaceb8",
          "md5": "ed60557aa3929823e6741c0bb733bf42"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0.klib",
          "url": "core-js-0.2.0.klib",
          "size": 61766,
          "sha512": "d22918ed86bed2c66f477298cf823817b04717dd4a3c49d5b6d98a4e495bedf62915dd805141c3f1cd192bce1ec093dec270eaf15c2b063e6950a9844a9a33b5",
          "sha256": "cc9fac0e8962d5bbe8e67ca984f0aab77941f0cae7c15e473641645503324a2a",
          "sha1": "3d6068dcd6d46b6d868d859344dcd6ddfcbaceb8",
          "md5": "ed60557aa3929823e6741c0bb733bf42"
        }
      ]
    }
  ]
}
