{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchossimulatorarm64-0.3.0-rc08.klib",
          "size": 203136,
          "sha512": "f234a48abf6e078585a5f6af25f873fdabdd41573188e24b5633278deb247b8a588b529eb62cbddc8c9b9b991bd7bc7c8e3af15e7f96e68dab513a26e4a1735d",
          "sha256": "6f0020d554dac63dc6cac2fc92f538fe4b20fb1c863e7221c81bb4ddf0965b22",
          "sha1": "2910a6c7136b64258d870dfba8d9c477119ffa90",
          "md5": "e4e1c1c616ca8e2560c996dfe481fc00"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchossimulatorarm64-0.3.0-rc08-metadata.jar",
          "url": "kmock-watchossimulatorarm64-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "f78ca4f4c0c6f458ce5f348a3b0f893731683bdc0853b2170af9ee587e6ff0631a5cb495f69246b05102b720b3e1e27c11ad2672be879ebbb6fa467a71a68da5",
          "sha256": "280b3d8e0910a3a9cb40725eca0cbd3f255e0943259559655fbc9ca0f0b7464b",
          "sha1": "e93dd8bf49f9e224f24bcb312ca668dab9b9bc57",
          "md5": "999025ae3a06388c86f31f95604b7d41"
        }
      ]
    }
  ]
}
