{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosx64-0.3.0-rc07.klib",
          "size": 202489,
          "sha512": "b36829b1e46b6da8e88cdd7a9d8a9786a6e0ac2243853bd72cade94b31fc9182d1818f2ac8d5539517556a0e0e08cdffb2e17067b019849d66ba85014b1a4a43",
          "sha256": "f535abfcbc76e3b433c265659b34d6b292ead5bf5a1d58080985dfd2ca550f98",
          "sha1": "3c4319285f6be4212be1066acb250222408b3865",
          "md5": "43843f1169427e16456e83d54ad17260"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc07-metadata.jar",
          "url": "kmock-tvosx64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "2967a126515f76b7ee1c5edb4bfc1311e4eb172102c9b3d440188e114d0bbdb58a7b3a3b7b53d7b728b28c2eff196bb4ac06bf77f29ed12aa579dc8d1868005a",
          "sha256": "94c33bbbfcebf8d7dabc7176121f601160ec310a03ed4ae73723787081552ca3",
          "sha1": "7cd7c51b15bb718bbca2bd6b6def2e345b1cb08b",
          "md5": "1b8965e1a25f9e46dc5d93bc989c8f80"
        }
      ]
    }
  ]
}
