{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm32-0.3.0-rc08.klib",
          "size": 203016,
          "sha512": "a393f423952685a0792885404d70a3578ec08122a77292c5670cbcff98ac2606807fac80c73d59cf4ac62faf084654ec0a715ed6d3dd791a34b3c652a48933d9",
          "sha256": "43e1f2b5f8dd786427c158a73e6c0eda2bb58a3b91a4090adee93b99e1d6671f",
          "sha1": "51d7e980345e29aacfb518849def6f99165d95d7",
          "md5": "fe0c9cc38e1bdaa6e40c96b6e784ef74"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm32-0.3.0-rc08-metadata.jar",
          "url": "kmock-iosarm32-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "b5bb9d14d7dc9e5539eb122f64b1e5b33fd01bbac22e92fe851ab368bbf41ff88ff25ad39aa3a579825ae68abb1db2b7cb6cc7c2450363c027cb0506c8e33157",
          "sha256": "71686427e2e2f2ed8fcb3409e39c32bc922480b9045aec061d895df23f1c7380",
          "sha1": "114f52ab02bc2c4f2248d435ebeaab88f033f7ac",
          "md5": "b4597714f61e2dbb1a25e73612e8fdf1"
        }
      ]
    }
  ]
}
