{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvossimulatorarm64-0.3.0-rc07.klib",
          "size": 202591,
          "sha512": "ba60be0b1a851239717e36994e173ee7cdd4fa1f310218281d0eefad16ed424b5dfefd56fc791e23c3feddd43ba0fb4fddf40d7a1d85a7b5f7769f5860fe042e",
          "sha256": "8f00fc0864774da5fdbceed7e232f8fdc54617bc3e305b461b381d97ba073ff1",
          "sha1": "c1ab32f32e28e2e20fed341663e343ad35a57b80",
          "md5": "1f579ab0084c6d5b717ee63a1335b269"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvossimulatorarm64-0.3.0-rc07-metadata.jar",
          "url": "kmock-tvossimulatorarm64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "7a8402dea1ea572a635dca361e90570e0da6aeedac4eb9002fe4dd0a05db83026323de6385b0f2e98ace924b695167a095c8efee8c0bba558b74ae89771829a2",
          "sha256": "39cb4ab9895b5d3762f009a4c0ec9efcad355829a2d5eb991f65c57bf2c0d01c",
          "sha1": "3a0910febbd80617af0c6a6988a8e05048439917",
          "md5": "3c25461c75dffbc4625f10ea66c4a525"
        }
      ]
    }
  ]
}
