{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx64-0.3.0-rc05.klib",
          "size": 202515,
          "sha512": "b583253a2919c677a101fb58b16ad327023633d83e81cd0473824aa76044361e73b38d90051cf68cf1a2cfee12f1396d7793beb47ba15e21ba1f9e864ebe09d5",
          "sha256": "8d07c363a5967d463512e69ec9fffd3d98ab6d154fc5508150a89572f5c3bd3b",
          "sha1": "6cbd32be326d36a712bd06355074527d3a753767",
          "md5": "729e42ae8adb9e51ec627c237ea69934"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx64-0.3.0-rc05-metadata.jar",
          "url": "kmock-watchosx64-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "704b526a3d80bf7cb4cbbebdd2127da3ee3fe97363b12e43b21da7b62ae415cb32c2758c67d97c62789ff9822203d12a99a17eec4a73015b87ff8ef4b6ee6618",
          "sha256": "d6745dcd50754d7cf7b3fb7ae480ad0186487bbbc40442fa40517608cd825593",
          "sha1": "2335be4993ce42a1209a47bb705c67903959db74",
          "md5": "5f90f08677a89a171deaecba72ef7dc4"
        }
      ]
    }
  ]
}
