{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1/core-0.3.1.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.3.1.klib",
          "size": 99958,
          "sha512": "cf01e577e57aaabe6b5b26992ebcbe05b10f371e27f32e1cc5d34bd0ae2baf952e060e329953bc512c22b5026041fce2e83affc8cddc587e401d56eb8ff33686",
          "sha256": "159a94b8066fa03e93d3868bad280cfd44221f3a2052fa664044f3d723221b4a",
          "sha1": "53cb4654a9782a752016466302d4e04f9d895e5e",
          "md5": "1a56a0bad06fc5acc66e60366c16c24a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.3.1-metadata.jar",
          "url": "core-iosx64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "68e9533dba69e44e1ec303fa559d0b89d19810c0e23c55454c30564be56d93e5aa82578d0ca1cdb9a7799f31cdd77243616f4c48fd5f0cf30b58cbfe750a7a90",
          "sha256": "76f66dc9cb76525a450edb8a0911f341d5a487368b82ef78c78693932aae09c1",
          "sha1": "f4b22bb96783349de4c51b587550ebd37c9498f0",
          "md5": "7076805d03b660ecbbb602ad5cd576ad"
        }
      ]
    }
  ]
}
