{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1/core-0.3.1.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.3.1.klib",
          "size": 99975,
          "sha512": "9e2c89f3208b252a4734d13e3fade4b4fbad79998867964b3b9b36a71046d1d333ac2ddc90f6185f488cff79901a9eecad04a6e5362c66df8ee6a6a091c7bce2",
          "sha256": "bc938b9875dc6f8581e56dfbe6808ed983d38006f4faf2d59f73a333682da366",
          "sha1": "789691f6ce6cacd2965c20d19c1cef8cf6aa6b2b",
          "md5": "fdc32d98fea5761322a50c8e3f3a0c41"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.3.1-metadata.jar",
          "url": "core-iosarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "e8d32af222c8442b9d9d263da327deb79739d1cf615f7e4b92d123aca75ae82aa2a100f3b23d6c6b36d616e2791609815416040503c23575fe999da74ebbf2cf",
          "sha256": "360a075476f56d2b1f472306d862221478c1767457a50eab60f1032987dd7ec7",
          "sha1": "b86b04bf05d42d5de5ab339f33fd8364419051f3",
          "md5": "41991fced55a7c1e3c4eb9ebb0e63c11"
        }
      ]
    }
  ]
}
