{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0/core-0.2.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0.klib",
          "size": 50835,
          "sha512": "c77e6bd66431abfd303a4f481af99f8e606068df17bc3989fcbae900f4255da4a16d692da719d748640409377f2c0191a4ca09033d837187830ecd815c66dc3d",
          "sha256": "3e5b638dc8a49f74f748a26c3e2af4a0168a3dad580cfdb84b0e773f18a9b66a",
          "sha1": "20d835c13d30da617a16712f626314302ca60ec7",
          "md5": "09b7918c6898d900bc2899ac3731e730"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-metadata.jar",
          "size": 261,
          "sha512": "acd28c4ae59b1337b881e383eaee18ae1a92bf0129d4afed2d3bbbb29eee235cac3fad74dbc76f6b7ce6556b3561d7aa8177d70298aa599b7d419284c636d2c1",
          "sha256": "173e1224298360c9f27f149d4284d3f4174d931fb028a6cb09f2ccc3b39659d6",
          "sha1": "af63d9f1d5b0b606ecb3a0d4af4a7cc601f2c0b7",
          "md5": "f359dd589606e2541cd35f420c6e7ef9"
        }
      ]
    }
  ]
}
