{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-metadata-0.3.0-rc05-all.jar",
          "url": "kmock-0.3.0-rc05-all.jar",
          "size": 28226,
          "sha512": "b43a730e4b371dd04bba76ec82b51dfed0a70e113dd48fb399d1d0efdd4875f230f2ea46d29e8a2d89ed18ddb7db69a64988f9235a2ef308832de39abe50ee37",
          "sha256": "c10bc015402e855cecd7a902cea3392bcaa3a94d7d86df960ffdc09fbea8d5dd",
          "sha1": "b02687546ebbce092009739da7362040f6143b0f",
          "md5": "0ab140475f879bb4addbb4b0b858bb3a"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-0.3.0-rc05.jar",
          "url": "kmock-0.3.0-rc05.jar",
          "size": 47917,
          "sha512": "c337415bb84c3a822259429df1bb08f260b20fa2c9319cb6bf2cc43c70e1366cf620814a5c9cbbafe594924f5169b5835f0e1580a7e65bc7c66501c40f84b647",
          "sha256": "c265d8c6e923a30fc3c3db9e800ffdf04e4e6ad104a530a80f4b43d0d43492be",
          "sha1": "8779e3293b472a86eaa6537910c644eb9304a916",
          "md5": "4ebb459482340275a675a9a761b0aaa9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc05/kmock-android-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc05/kmock-android-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm32/0.3.0-rc05/kmock-iosarm32-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm32",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm32/0.3.0-rc05/kmock-iosarm32-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm32",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc05/kmock-iosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc05/kmock-iosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc05/kmock-iossimulatorarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc05/kmock-iossimulatorarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc05/kmock-iosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc05/kmock-iosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc05/kmock-js-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc05/kmock-js-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc05/kmock-jvm-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc05/kmock-jvm-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.3.0-rc05/kmock-linuxx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosarm64/0.3.0-rc05/kmock-macosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosarm64/0.3.0-rc05/kmock-macosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosx64/0.3.0-rc05/kmock-macosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosx64/0.3.0-rc05/kmock-macosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-mingwx64/0.3.0-rc05/kmock-mingwx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-mingwx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosarm64/0.3.0-rc05/kmock-tvosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosarm64/0.3.0-rc05/kmock-tvosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvossimulatorarm64/0.3.0-rc05/kmock-tvossimulatorarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvossimulatorarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvossimulatorarm64/0.3.0-rc05/kmock-tvossimulatorarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvossimulatorarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosx64/0.3.0-rc05/kmock-tvosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosx64/0.3.0-rc05/kmock-tvosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm32/0.3.0-rc05/kmock-watchosarm32-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm32",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm32/0.3.0-rc05/kmock-watchosarm32-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm32",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm64/0.3.0-rc05/kmock-watchosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm64/0.3.0-rc05/kmock-watchosarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchossimulatorarm64/0.3.0-rc05/kmock-watchossimulatorarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchossimulatorarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchossimulatorarm64/0.3.0-rc05/kmock-watchossimulatorarm64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchossimulatorarm64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx64/0.3.0-rc05/kmock-watchosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx64/0.3.0-rc05/kmock-watchosx64-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx64",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx86/0.3.0-rc05/kmock-watchosx86-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx86",
        "version": "0.3.0-rc05"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx86/0.3.0-rc05/kmock-watchosx86-0.3.0-rc05.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx86",
        "version": "0.3.0-rc05"
      }
    }
  ]
}
