{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosarm64-0.3.0-rc06.klib",
          "size": 202531,
          "sha512": "95a3ec6ddab894f63cf2e6f146ff17dd7c62454c0d6ba73e59fac97369be719ec0620a581e8bec09180e8ff6d4ba813e4c3b96e5e8a8511063754557f4b9aa4d",
          "sha256": "4399ce225e78e35ab6f87d377aea2330abd650e09fb29b66b0668adfc8e9702e",
          "sha1": "9565cdb2f2dda3754d4905b8c3e2be24703df9d8",
          "md5": "f4884de7191165a6fae2aa137bddc266"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosarm64-0.3.0-rc06-metadata.jar",
          "url": "kmock-watchosarm64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "6d7d1f4da9908ec431e5dfb8ad64333a3885194198b1d315367c9dd55ee91ae0febefda26f9476033a5509bfb3972dbba566cd1ad0fb31059c9c758da91a91d2",
          "sha256": "956e46cfb9b1e8a736e9d587d651dabe49bd6db6ab2ef8654bb3d93806284a8a",
          "sha1": "71cb9df64fffeadb6c45cfcb9978d9bbcef0d56f",
          "md5": "02fc8448820faa6a687c877b6e9e1109"
        }
      ]
    }
  ]
}
