{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-macosarm64-0.3.0-rc08.klib",
          "size": 203092,
          "sha512": "b15abb3127a442f8114acc5be54c5ace031a66390f5ac17112a00ccca9ab8862f228a62e97730a18a7847fcf6963075c62e781e6723e20e9a94fa5f96f1e2743",
          "sha256": "8101a551a4f4e7eb2792c0ead1bad5c3b9c1043f0b6272bb6b782cc3d0525a5c",
          "sha1": "9004cfe8e4eb570c574361fe813a6910c00dabf1",
          "md5": "629da6c4265ba3ba6b15ea7780cca7e8"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-macosarm64-0.3.0-rc08-metadata.jar",
          "url": "kmock-macosarm64-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "a65c261a33fa6520ee557e9fcde53a13503df3b8744ea12464cd6f59dc1f8583671fcbb4737f2747b69dd328f0de74f137590276b59acd3aca07cfeb6788ce9b",
          "sha256": "8b152800121efcf6b0a83fd0dfa8fd1a9f4001339aa8787b6becb27a6cf4825e",
          "sha1": "4f19e80f3006d0ade1cb9aeb0a068a5b5ab95aed",
          "md5": "3180c29eaeba35a29436e31d9983523e"
        }
      ]
    }
  ]
}
