{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosarm64-0.3.0-rc08.klib",
          "size": 203025,
          "sha512": "eff87ff1b191cb742fd4bf04a1c3c48d96a074f9beb83b61f0a45d724ec4f9455b5434787da1ca624c8ad732ebd06f6782b2b11332d0dbde196c5be3d4a3a889",
          "sha256": "c092d814313028ba7d3971bbd57ecd37ea8c3a2bc61d38e2d946a908a432b09a",
          "sha1": "76b91b6f2ec1d1076372e02c865a6e413a809fb5",
          "md5": "ac506c6511649cf944d15377746f0648"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosarm64-0.3.0-rc08-metadata.jar",
          "url": "kmock-tvosarm64-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "f77e71a03d41125ed53eeae3fef33e21fffa6a882e6b1615c34138c2021f6ba2c0ac4d0136721685f1f7795d83b188dc2144c2f9f0c338d9eda45a03776b8644",
          "sha256": "a4dd97b90f98e92b5d4e882310375c02c5713f62a49c5c67cf014cf7524a47df",
          "sha1": "8b7282c8b140eb3ad5f7ba618adb9ccbe4cb1fb6",
          "md5": "3dbb1407660a78ddc3cab00f6f1905c2"
        }
      ]
    }
  ]
}
