{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.2/kmock-0.2.2.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.2.2.jar",
          "url": "kmock-jvm-0.2.2.jar",
          "size": 395086,
          "sha512": "c572301ae595e13fd3a306fc0d24c423664430401fc17fbf518a2d694583c4d98e70cc60d01aa7c0fe025efad9a1f14da03994edb0d5ac75f2af43595008b407",
          "sha256": "73725e04b57c5b32a2b7b658f3a3a963f4bcc360332eb41a961c590d1aee7740",
          "sha1": "7684675f92407205247e9554da9578e2cf5e6955",
          "md5": "2a2b9164eb8f6488c0e9d886165aeeaf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.2.2.jar",
          "url": "kmock-jvm-0.2.2.jar",
          "size": 395086,
          "sha512": "c572301ae595e13fd3a306fc0d24c423664430401fc17fbf518a2d694583c4d98e70cc60d01aa7c0fe025efad9a1f14da03994edb0d5ac75f2af43595008b407",
          "sha256": "73725e04b57c5b32a2b7b658f3a3a963f4bcc360332eb41a961c590d1aee7740",
          "sha1": "7684675f92407205247e9554da9578e2cf5e6955",
          "md5": "2a2b9164eb8f6488c0e9d886165aeeaf"
        }
      ]
    }
  ]
}
