{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc05.klib",
          "size": 202480,
          "sha512": "b495b66a1d4b242e2aebbc7b4f0a65ed69dd4c281b396373c71cb4a71d577ec034a1a67ab6b9f0f231b4c4635b75fad18669e680a34326b2e3cecf2f41a9aba9",
          "sha256": "a31ea5c8ad83ca406fc521654cfb23f89eb2c00205dd5d105f79d5c9d9fe84c7",
          "sha1": "6c118f897b3f54a1bf78e404e142b01a4ecfb0cc",
          "md5": "989aa7dcf21814b1e79a3dfc3b047188"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc05-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "55c2fd1dc69c6892b8d02754859dde39777f1894b3336999e1b0a2d2ad0be5dda915bdb86415e30e8fa7e3b7cf7cdda9c8e9c347f73fd1aaaa69084f38078a29",
          "sha256": "d3bc9ff2db931b89283b531d3c3e466ceff392971d522feaff7347ce9a298fd7",
          "sha1": "1582164daec917c96028d2e93f5b395769b39a5f",
          "md5": "aa08f8122b014384e40be755f9e7952a"
        }
      ]
    }
  ]
}
