{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1/core-0.3.1.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1.klib",
          "url": "core-js-0.3.1.klib",
          "size": 123780,
          "sha512": "493124a147a9f5a524f6ea816d9eb8e2721f7e007856260b0717a504dbf987a4012e5fb6e545a8097565ff46d1f5159314b6e457d278a9b578c2b3493b72e5ee",
          "sha256": "155f3f6c8b6c4488430abf5f918c78e7c47ae63c37ef209d0da6dc8587276b78",
          "sha1": "55798e593cb785931b254a1c0a801cb354550dd7",
          "md5": "654f7f30a77af0217daf823e0bacd46d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1.klib",
          "url": "core-js-0.3.1.klib",
          "size": 123780,
          "sha512": "493124a147a9f5a524f6ea816d9eb8e2721f7e007856260b0717a504dbf987a4012e5fb6e545a8097565ff46d1f5159314b6e457d278a9b578c2b3493b72e5ee",
          "sha256": "155f3f6c8b6c4488430abf5f918c78e7c47ae63c37ef209d0da6dc8587276b78",
          "sha1": "55798e593cb785931b254a1c0a801cb354550dd7",
          "md5": "654f7f30a77af0217daf823e0bacd46d"
        }
      ]
    }
  ]
}
