{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0/core-0.1.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.1.0.klib",
          "size": 50697,
          "sha512": "87ab0bfc6e8d903423c3be3510c17346d5c6eb32c3e561afb093fa62e10ec1278f5ea5f2492cd5bc26a27c1fa415b727a4cfa28ced6fd4ca2ac37fdb04ee47e6",
          "sha256": "dce5e6c07b8cc6828cd72cefd3e1a1093f30fcdc3cbd9e64a55f0dbdaf89198d",
          "sha1": "e0fc0161455b59a13dc26f03f9c235a9411d5abf",
          "md5": "123ed70abcc8d622409ac4d1021195e8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.1.0-metadata.jar",
          "url": "core-iosarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "c5ec22bc11ff5ef97ead79d5f324de9ef6b97595486e5170d48c96fa645f8eb58f551b3a2d5b58e8d88b220968ad8afbfb5df3845cc9dc5857f1648fe389a084",
          "sha256": "4faad09a750130e36b22fb722c53de781fa9a3bea118353ad53161b78b4453b9",
          "sha1": "1751953a6c6f4c3297fe11a63d7b043fed86eb6c",
          "md5": "34a937e5d6bd039625333bf033bf694e"
        }
      ]
    }
  ]
}
