{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm32-0.3.0-rc05.klib",
          "size": 202496,
          "sha512": "0fd385828a58c70a3ccb0e2833125eddeab88b5df66ae2d263276419e1ac4ad4a68de0e5462f62a91c8365b065acfeb9d064c3b018ccb94d7ba85d6fcdce7a60",
          "sha256": "c462c940a1079fd607471f50131abf4e2b5e9b625fa448286d9d0de452d71d86",
          "sha1": "983be6d7714423ccc979618ec70c15226c00f889",
          "md5": "a788d917743973d54e06986c1882bc24"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm32-0.3.0-rc05-metadata.jar",
          "url": "kmock-iosarm32-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "58d44efc50476fa1cb9ca74c6a99b5cb70b444ba057088745eea611b73369cd2579a1a86ed12a0db5aa79981044842280da40e26ce82e4f9ba5070714f69ea5f",
          "sha256": "21ecc00371b09b6ee87698a1cea1b1579ebe2e2830d4e7c4b2532f9eb82ec6f0",
          "sha1": "8033d4a2a241e57a68a5959510783aecd81b49ff",
          "md5": "b3198c41dc99240832825ee119eb7554"
        }
      ]
    }
  ]
}
