{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0/ktx-datetime-0.4.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0.klib",
          "url": "ktx-datetime-js-0.4.0.klib",
          "size": 39983,
          "sha512": "455dade92fba3a53bcc51281cb07c6a21d5cb4a6d768e55b6a35484016bb608489a3e549f40ce6367dfa87b91dbbaaa4995ed5c4565fd659444e35774e6b8f28",
          "sha256": "94fd847512f661e6d12acc01f06176fb66c78f9c33457274243e804d04e40784",
          "sha1": "2c529db97481d48f3b884bbf4f48e7cc9fdafc3a",
          "md5": "78b389780b74eeda6dbd0c93ea0cf217"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0.klib",
          "url": "ktx-datetime-js-0.4.0.klib",
          "size": 39983,
          "sha512": "455dade92fba3a53bcc51281cb07c6a21d5cb4a6d768e55b6a35484016bb608489a3e549f40ce6367dfa87b91dbbaaa4995ed5c4565fd659444e35774e6b8f28",
          "sha256": "94fd847512f661e6d12acc01f06176fb66c78f9c33457274243e804d04e40784",
          "sha1": "2c529db97481d48f3b884bbf4f48e7cc9fdafc3a",
          "md5": "78b389780b74eeda6dbd0c93ea0cf217"
        }
      ]
    }
  ]
}
