{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc06.jar",
          "url": "kmock-gradle-0.3.0-rc06.jar",
          "size": 75400,
          "sha512": "2a4bad273137792b2ab557dcbb0b8fc52f5abb22c670619a0ac3c0371619fe38f51fdd8533fde2778eedea5a734b3eff359ddf01429ad2069f7af73aeb669e7d",
          "sha256": "d32ac450cb6125db02a7a81187917722d322c6ca0bdeab9fdedba59ec5d160fb",
          "sha1": "c4e930aa5974488f254688eec7a6fc0aa6e7116b",
          "md5": "9c172d3e6bd42c2ebf1933e310ac0f48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.21-1.0.8"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc06.jar",
          "url": "kmock-gradle-0.3.0-rc06.jar",
          "size": 75400,
          "sha512": "2a4bad273137792b2ab557dcbb0b8fc52f5abb22c670619a0ac3c0371619fe38f51fdd8533fde2778eedea5a734b3eff359ddf01429ad2069f7af73aeb669e7d",
          "sha256": "d32ac450cb6125db02a7a81187917722d322c6ca0bdeab9fdedba59ec5d160fb",
          "sha1": "c4e930aa5974488f254688eec7a6fc0aa6e7116b",
          "md5": "9c172d3e6bd42c2ebf1933e310ac0f48"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc06-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc06-javadoc.jar",
          "size": 261,
          "sha512": "51da1a0790d5b125c6dfc45582a44b1748a2476b1ac5f610d498321bf9c7cedab0487c01d9570e0cb632d153c33f552d5f0f6eda4bbf558b8ec118acca02b1d3",
          "sha256": "6a2f5c2594b72c321606835262fc7061bbe02b47af91eaf841384b451959f78c",
          "sha1": "2ebba2b0dc938b56a309f36fd83bcb89a39844a8",
          "md5": "ca7a2600de520ee9876df6cc5f217ac9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc06-sources.jar",
          "url": "kmock-gradle-0.3.0-rc06-sources.jar",
          "size": 14699,
          "sha512": "db2bb1b8ab2d675b44307fe251d4fb1cbdf9ddceb8cd7c76f92120934c1ee376fc7178a48187da2f98547875766145762d52247fac5423610c9404ddf5a77c93",
          "sha256": "9a25c462e54c69c9fbb7a8a98bec6a9d7e208858aff994949d1df7a0f2817143",
          "sha1": "45db18adf6cd641885a0b213c2380ef57cc5d03b",
          "md5": "907cebc977605abb048ff72a4277c524"
        }
      ]
    }
  ]
}
