{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0/core-0.1.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.1.0.klib",
          "size": 50680,
          "sha512": "ce38700f9023e322b3c2a996c4a74a5a27d0bce4350e44092801cb7f13271c4d51f3eb592caab1eaf015dbf2dd0ee27e4a28523bd11ffca5cb84f73f562ee2e2",
          "sha256": "ac666f9b9dfa195418eb7dfc1bda0b169b7ed025b4fc42bcb66178966965c846",
          "sha1": "8af6147147d9802735c044e6de247c848e4f07a3",
          "md5": "2f8d7bb71e14f819a9f7b4c86499f296"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.1.0-metadata.jar",
          "url": "core-iosx64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "c5ec22bc11ff5ef97ead79d5f324de9ef6b97595486e5170d48c96fa645f8eb58f551b3a2d5b58e8d88b220968ad8afbfb5df3845cc9dc5857f1648fe389a084",
          "sha256": "4faad09a750130e36b22fb722c53de781fa9a3bea118353ad53161b78b4453b9",
          "sha1": "1751953a6c6f4c3297fe11a63d7b043fed86eb6c",
          "md5": "34a937e5d6bd039625333bf033bf694e"
        }
      ]
    }
  ]
}
