{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0/ktx-datetime-0.4.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosarm64-0.4.0.klib",
          "size": 34700,
          "sha512": "4e6e63a1280edd24731208db185207b3e32c8f468aa792ddff68834c261c94c19895c0c1ad720e44c4d3a4c741ce79261fa5befd35936c169dd7697da7633a25",
          "sha256": "57c307e57fe3914a46433eb713c8a3a58233beb481dd6afb7a59bc8259b25dc2",
          "sha1": "dd68411fcc361e03792d63096d349ab6e0a009f9",
          "md5": "958e861da164188bdf55170df1d61328"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosarm64-0.4.0-metadata.jar",
          "url": "ktx-datetime-iosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "4e150cc5373d0931b26c0cd4fe624d5744b7e65684f3bdaf8ebc7ded5c73d1dfd18dd8b8e797a92367e9e27b9e68cbaf7f7416df051554eeb481a0409f697b1f",
          "sha256": "1b67a191871dbdbd8ab80279bb67ea4977053208b9781b192e9ea338103c7695",
          "sha1": "16d06f991b654f596db73855ee7f3f82f6cd20a9",
          "md5": "3b73088c98e6fbcc36304534a086de1e"
        }
      ]
    }
  ]
}
