{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.3.1-all.jar",
          "url": "core-0.3.1-all.jar",
          "size": 22410,
          "sha512": "2f22e340322247ec5e8a4321b8dbc09350fe361fa10be0528e164adfe394dcd8c700e4e2e047ea21753bd389e7c67f6d86b6c7af654798a83105a50a474ffc60",
          "sha256": "c96501491184331a54ec55f1fc5270c3e7954d0e15ef1621756c3c5ba62f8a9d",
          "sha1": "a8ab49f14018153b7a9617c2b62c1166db33c227",
          "md5": "2a89ddf1bf09c455a26f0bd41a47b699"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-0.3.1.jar",
          "url": "core-0.3.1.jar",
          "size": 37352,
          "sha512": "32b75bb3f2002b99a88d4aaef36f2c3fdf21f5131bea2822dfa889c2d248d82c0b929e5898f4b800dd6c458f996a42eb4c71d2b74cfdc2bdebd7a23f7ec49fd9",
          "sha256": "a94654ac2a55bf9103baf864967e5ae5fbe86167480cc77691867dc9cc38237f",
          "sha1": "55cb8be1dbe0455107b663075ed6eaa791809721",
          "md5": "00da232bff1e22cf3715a0e72144e82b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.3.1/core-android-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.3.1/core-android-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.3.1/core-iosarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.3.1/core-iosarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.3.1/core-iossimulatorarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.3.1/core-iossimulatorarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.3.1/core-iosx64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.3.1/core-iosx64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.3.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.3.1/core-js-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.3.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.3.1/core-js-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.3.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.3.1/core-jvm-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.3.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.3.1/core-jvm-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.3.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.3.1/core-linuxx64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "0.3.1"
      }
    }
  ]
}
