{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.3.1-all.jar",
          "url": "core-0.3.1-all.jar",
          "size": 22410,
          "sha512": "7d262482d0237910726a11ba14f9eeaef7601668382bb816cf0329fb57bc339cfb6f9ef1da0b197bfa064132080176527c5d75fa233cd4ff213ab51bea1ca9a7",
          "sha256": "17c782863b25e16f635c33900c342824fec0f89b8028bfe4515d43ff5b8a09fd",
          "sha1": "a5d34a52e09880eb2e5311833aa8681e751f61b7",
          "md5": "c020bf38520aab3c7d11ec501f1ed54d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-0.3.1.jar",
          "url": "core-0.3.1.jar",
          "size": 37352,
          "sha512": "abeaf2bb6a093bda37c7e1aee6f030d2dd22b454a998c27ebdde5e150469dfc0150bc72855db70f82c5b5ea98d5c472c2f6fdb5d668bedaf220401eba5bfc4d4",
          "sha256": "886592fad09121aa886f7709d6d33702d0a2bf5ca21b9fb30e8abe027b11dade",
          "sha1": "20c6cc802207e84b4ba0fb8083b2574db8c7bc09",
          "md5": "bc35ee223292fb3c9800e62a8e01c5ce"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.3.1/core-android-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.3.1/core-android-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.3.1/core-iosarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.3.1/core-iosarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.3.1/core-iossimulatorarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.3.1/core-iossimulatorarm64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.3.1/core-iosx64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.3.1/core-iosx64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.3.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.3.1/core-js-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.3.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.3.1/core-js-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.3.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.3.1/core-jvm-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.3.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.3.1/core-jvm-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.3.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.3.1/core-linuxx64-0.3.1.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "0.3.1"
      }
    }
  ]
}
