{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchossimulatorarm64-0.3.0-rc07.klib",
          "size": 202617,
          "sha512": "364ea918873e2d21d16599447a45303559fe2ad079d17955b049d8d388903b27b3352cb5b0cbf6c0219408c3f051e431c9dcfb37a10978f9b8e66ce26d161595",
          "sha256": "eaa23e2c15c3c7addd16ca138b6cc74143a19c0eb3ae622d461b7352fb0b175c",
          "sha1": "6f9249540cdf23ed96f91111bb4f933418c1be30",
          "md5": "ce67e8329e230a1eb970c63ffdf56dfe"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchossimulatorarm64-0.3.0-rc07-metadata.jar",
          "url": "kmock-watchossimulatorarm64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "55dd1b0ffbbd2cb63d3606baf4578e07762b2102731d4ac3c890257d223f9f4454fd80251f9c1357aedf3db7d733e47044827179a472bff2d701ce9ac91ec6f7",
          "sha256": "b830290c883f554dad52b851e157bcd97a6937f87a4beeff5c7990ebfd8746aa",
          "sha1": "d0066aaf1b93dffd37bea70d8299b11293140752",
          "md5": "6d73f633d3f0a0c48f4ffd6be16bc6cf"
        }
      ]
    }
  ]
}
