{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosx64-0.3.0-rc06.klib",
          "size": 202489,
          "sha512": "b6a71460f26a73c9497b6659a899be7d4022a78abb211e68635ee94484074b55029fd86d433f110d9fd1516f34aeacc47d477bfaab7ef63d6c27bb28feeec21c",
          "sha256": "c93bb6608bc9cb60bf6ecb481c6ba698cdd033a3cb904c0dbaf40f39f9c76f02",
          "sha1": "8e257ceb1a5310eb0e58176bb91778ec14bc68fd",
          "md5": "b3465ed15b834bbebc197b9a54f947ad"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc06-metadata.jar",
          "url": "kmock-tvosx64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "7adf2347077e44d647ac32d2ea1970a391017477decb3943b670d16de299edd700d992b023e5dab8dad745eba91e67f11369e0649caec8d83593a653c0a1d009",
          "sha256": "0f7788293bd845b53248b69e4d0b62e2960df34093b3ca54a6c7526af0462532",
          "sha1": "a07184cf4d8be0a61f1b2f76e7d5da0083414194",
          "md5": "2252aef3a753e8756cf955d7d688ddea"
        }
      ]
    }
  ]
}
