{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosx64-0.3.0-rc08.klib",
          "size": 203005,
          "sha512": "31123bfb0f561642ebd46d42f6091a46966a859c2bc11f90a89dc85163dea9fe70484303aa691f43d3bebd16c81383a72796f18925927763c54516a82221cbb7",
          "sha256": "1b31ee75427012aa16729fcfb7ad49c8fa0c21ac3055a2e452bb50dfd0f708a6",
          "sha1": "a2052998ba9ef8ec02bfe46d22d98fc3379f9bb7",
          "md5": "a0ac4fb35982e1096b30ff00a6551425"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc08-metadata.jar",
          "url": "kmock-tvosx64-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "3ba3415e0bd0acc56e66f191042672f816860c94f5990b1e8dcf75933b82f18307458747806cd35aaf77e4c724f30dbd0a52e30b2cf2f722cb4963f7a5474742",
          "sha256": "665afb913d3a514265a589d21441eeb6af0d1f071a2d34e76c88d3a45c311c91",
          "sha1": "fff25a0aaab7f4189d815495df0c2770771e553a",
          "md5": "f8509ab079da51ab9af2da2d42a14fb4"
        }
      ]
    }
  ]
}
