{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1/core-0.3.1.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.3.1.jar",
          "url": "core-jvm-0.3.1.jar",
          "size": 251485,
          "sha512": "071de25b5e0649872686057db8d57fe0a1c85f534db4c313c4d900d19948aa54d5dcb8a44754cbab6e8ddd4eaaf29253ebc19824f0b93fd32ae4f9355c9e6a21",
          "sha256": "98d9ed671945a3a990278efeea918d5d12779c40afa225464b71c81889b1fb03",
          "sha1": "b1c49eebf35c1b59e037343e2f0d4cfd91bd6270",
          "md5": "1be69f9d874df31da66d870c16f25857"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.3.1.jar",
          "url": "core-jvm-0.3.1.jar",
          "size": 251485,
          "sha512": "071de25b5e0649872686057db8d57fe0a1c85f534db4c313c4d900d19948aa54d5dcb8a44754cbab6e8ddd4eaaf29253ebc19824f0b93fd32ae4f9355c9e6a21",
          "sha256": "98d9ed671945a3a990278efeea918d5d12779c40afa225464b71c81889b1fb03",
          "sha1": "b1c49eebf35c1b59e037343e2f0d4cfd91bd6270",
          "md5": "1be69f9d874df31da66d870c16f25857"
        }
      ]
    }
  ]
}
