{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.0/core-0.3.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.0.klib",
          "size": 100072,
          "sha512": "d1e3551779435d6ac8016acab391055d7f34fe5ace6c75305ea0851b723a0843fb22c8aa1a7a45d1a978f395bb6e4ade9be93fa2eee7877cc8cbf79ce3f20db4",
          "sha256": "6d41a38bd9385b69c96c116e12a60e1d27bdd4bdfd655ddd0c06a3c24e813029",
          "sha1": "c034261ab9e58e1cba3aa717ecc5e6d4970bb72f",
          "md5": "c8ef88ed6444af429c6b15c71def2589"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.0-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "85aaf918801d733f64877c87aeb58cd0cb20d9ff4caed1b37e494e92c5b45343cbb995bc2c649415d8d3164dfd2d88dd4fdf85ffd9fc016d33ae90d593cb00ea",
          "sha256": "b66b7e6799b82be9bab1296f8165d148fd59f4130c94c97c120328506b29105b",
          "sha1": "50c053ed827de507434a657db67c517d1e8da0ea",
          "md5": "46996d7f4f9bc09d6a4ab1fd82867918"
        }
      ]
    }
  ]
}
