{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0/core-0.4.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.4.0.klib",
          "size": 110182,
          "sha512": "143bc4c59d99954e326df52f1b0e6cd88f35265a19b3d7d4f4082a5c9c8df795879e73421e99b698da4ee140bbfa9947bffd9596e283a35e56b323f86197920f",
          "sha256": "1547469ed1c53e9d41b87c611814fff814aa3d7f443af0cd2007e95915c24036",
          "sha1": "732daadfb85a3a2b372119f6bfb07e5f0e22328d",
          "md5": "f5605e937d2c079f02c51a0895485ff6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.4.0-metadata.jar",
          "url": "core-iosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "01b2e3e638b3aa4791374db0822d8a37d61c61f95503d4e46f9bbcc827f464a08cf04eaff6e65fc94500112b0b91116cc3ad84f694f2a8b453d25c49f44ddcbb",
          "sha256": "99677aa96f84b3d93a7aa2ad2fdfb485a4e8a82f43d2f257e069b2d6f44dcacd",
          "sha1": "d2cfadd3896a3d9c5336d24d3be352921f57f1f0",
          "md5": "2b1bf94d4dad3dac6e2a81b5fb0a8551"
        }
      ]
    }
  ]
}
