{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosarm64-0.3.0-rc06.klib",
          "size": 202505,
          "sha512": "34965a58b2832ad673c4a35ff59d6b611c55ba93d42c626712dc8663d046986f85b18d7d30f84132e12f012de9a84fce4f56d3f71df1087a544d9f375c252a69",
          "sha256": "9e3da724ca70630b6fb5761abd5fb594bb881de8fbde6dd64c58773bf64cd937",
          "sha1": "fc454126b8d2fc8df4d54b93e9909bc206d01ae5",
          "md5": "04036cbf984638edf5e436b0302cf301"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosarm64-0.3.0-rc06-metadata.jar",
          "url": "kmock-tvosarm64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "8128b9361db3a010c765b7679eccd9649e0c10e662fa8023e59b2c40610c6fe1c0fc22c483031bd4b258d31e9f4c2d5513a1cd5b29815d8124f3c136cb1587c8",
          "sha256": "5d93c34b3126fa228498e4e845d0fd496165870168f3c64159c3bb04e76f64fc",
          "sha1": "507a2bc233d267c4c2dc37258847735d31b696ac",
          "md5": "d6f946079275a238b3cfdba1381664e0"
        }
      ]
    }
  ]
}
