{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosarm32-0.3.0-rc07.klib",
          "size": 202531,
          "sha512": "646ba20267e7bbfea445c7f34452e6705a4929fa6485613fa9bbd07593c5a60db6429c6297423b821a67ca957fd11448c7113f9e1fc448ea65141a303114b3bb",
          "sha256": "4112a9d774d9f67d22628be3f1cea02b6cfb6508bc268e5a9768cda4c88260e1",
          "sha1": "67a71b8d68bbd2dff40496e36580cc55f6d529e1",
          "md5": "4d7a16f764d78628cb1a45add02f03a7"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosarm32-0.3.0-rc07-metadata.jar",
          "url": "kmock-watchosarm32-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "db9f293f88776d8e072ea1b4b8cff6219a9f00527c1e8af6c4026d2068f6eaacc8665326fb3edfe2682fde2be4eb0d483895eb39652bb4e7d3f3a48a4ed95214",
          "sha256": "3d96d070bdc37769b206b9cbc5e7edd236fe1f2ab2525de0b6d06f95d26cb06c",
          "sha1": "89d0e5c43ab488541602559a059dcf3b7c944d34",
          "md5": "f1417e0ed4f5d81abd4f0072644f1506"
        }
      ]
    }
  ]
}
