{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05.jar",
          "url": "kmock-gradle-0.3.0-rc05.jar",
          "size": 75399,
          "sha512": "584a07f35f84bd5c3e8e2b51483b9293cf93f398b890540f1dff8fe2fbbae893f3fce68616015372976721e82642d47656d0e92c79a7bc361c03f8407985b552",
          "sha256": "b9813f33f2c6af878344b881f355d400d1aa429cb43c095beae3af78a2fdc48d",
          "sha1": "81f12103637c3b03586804a8d86340c91908d46b",
          "md5": "a0761f8bf364e3030da0ff6cbf7494d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.20-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05.jar",
          "url": "kmock-gradle-0.3.0-rc05.jar",
          "size": 75399,
          "sha512": "584a07f35f84bd5c3e8e2b51483b9293cf93f398b890540f1dff8fe2fbbae893f3fce68616015372976721e82642d47656d0e92c79a7bc361c03f8407985b552",
          "sha256": "b9813f33f2c6af878344b881f355d400d1aa429cb43c095beae3af78a2fdc48d",
          "sha1": "81f12103637c3b03586804a8d86340c91908d46b",
          "md5": "a0761f8bf364e3030da0ff6cbf7494d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc05-javadoc.jar",
          "size": 261,
          "sha512": "fd85f760d94d3827d188a24d57dcec85e1980dbce9078cc492f742b249ccdffdc8ff4bdc81a260060ffb11a6c882667eceb65b2b0d1c6c2b69b77e5c5991e364",
          "sha256": "bf478dc794425aed34223c4364c524387fcc7b8d7ac0bc1e50ec8042bd972f29",
          "sha1": "d3a391abd152a167f6468d5f6072cf8c2cb10a86",
          "md5": "074286f9143b0cb9275028f349c2bc07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-sources.jar",
          "url": "kmock-gradle-0.3.0-rc05-sources.jar",
          "size": 14699,
          "sha512": "9caa0f46e93d383ac0ed35674a365735466f015b0d498f16d1ba8e2477c88af0f3a991b8dbb02922ecfdc464e969a0e9bfe1ef4f2a532d5501920bd1ae5a2ac2",
          "sha256": "eb68b4fe43217ab21e2fe4bc5ef7c3b9a770dd63a4880b9886b7e38b65d0ae35",
          "sha1": "afdc37976924573c1e61f665b3c83d472a17ebaa",
          "md5": "14301e4ffbcc8251aed8c021c95f225e"
        }
      ]
    }
  ]
}
