{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx86-0.3.0-rc06.klib",
          "size": 202515,
          "sha512": "4a40cf92ba3320cf50e0b2151f7123c98ed5f2655b14abecf02af06ce3a2d0827e257273c57d4e65f38d8f4e5f76f3610cc40c842c20d6c8c13bcc69d9777be0",
          "sha256": "98ef95384ae004bb9508242f030c8fca5363fec24a02f5157f77b7fe488836b6",
          "sha1": "c5424e35004251d96ea11c97ab6e8f9805445284",
          "md5": "94aba369dc1d9ea519a6bd647b1eeb68"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx86-0.3.0-rc06-metadata.jar",
          "url": "kmock-watchosx86-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "ee9bc56c66b9f3e8647489783e3684ba9bebb546d34738b3aab8346c1bd59f782e1df95bce28faff5bd2622c625d3a12b00c4e4b1179283b48ff8e5e1b473136",
          "sha256": "11532b48a04f5c541f2845800380aed59c91ff01e1d0743f1f0795204163026f",
          "sha1": "a099c4455c71e2f6296381366fc3f8313f72fd61",
          "md5": "8bef0ed2cf4e3e7614fd53699dd88b5c"
        }
      ]
    }
  ]
}
