{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-metadata-0.3.0-rc02-all.jar",
          "url": "kmock-0.3.0-rc02-all.jar",
          "size": 28436,
          "sha512": "f04f8d2fa85867ec416e5fa13e9e6959d4cca3dfd61d88b8b9d77f9325e4072ddbb80c2b626691e4e66b68d7d2988549520b5ec1b6b7df46bf636c7462946470",
          "sha256": "0aa3b210d9f4b0428ad603b8b0f036d8f40e435a5930cf6448f95672fcea80be",
          "sha1": "c6b9568847efb166dfaaa5a2f84111d1323c2ecc",
          "md5": "bd95fde60975a9ff8950daefc9e755ad"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-0.3.0-rc02.jar",
          "url": "kmock-0.3.0-rc02.jar",
          "size": 47914,
          "sha512": "811c2efbb9b29f88e5825ed2b8db3d994cdfb63f250acc101d340efd40c69fb58db53ade2293b34f6fe9035639b618c945168404e0f2fcaafdbe4dbde77398d2",
          "sha256": "9eb6d6ee5474769a5abc9ce42d98a9f566f20ca714b5a8d14499b37bd28d8a5c",
          "sha1": "a93bfec38d977f07cfc500b0674d1d0bd2acc994",
          "md5": "22fe6e2d22831faacd482b6c7cea8873"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc02/kmock-android-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc02/kmock-android-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc02/kmock-iosarm64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc02/kmock-iosarm64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc02/kmock-iossimulatorarm64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc02/kmock-iossimulatorarm64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc02/kmock-iosx64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc02/kmock-iosx64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc02/kmock-js-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc02/kmock-js-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc02/kmock-jvm-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc02/kmock-jvm-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc02"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.3.0-rc02/kmock-linuxx64-0.3.0-rc02.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.3.0-rc02"
      }
    }
  ]
}
