{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc07.klib",
          "size": 202497,
          "sha512": "d02aee8ebebbd566d74ec1912aa6f8c3b421f2a5d73076e0b63a98692ddb74d4717c1b8b9297109d2f374ec5f01c74836b12a56f4dacb090b07fd76ea4527bd7",
          "sha256": "954bffac6b8d2daf73f7892e8b6721be8c8789e97bd9e1ea44f4430ff1e4ed71",
          "sha1": "0ccfd4be7e51bbd7f31801e7a3c0f47db5f306d6",
          "md5": "e41700858a8f456f4b7270917086d501"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc07-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "138f47f22d8b3befc8522e6aebb2eb06c995854164a127beadff2a4524c5969c889b589fdbcaa45e58eb6fbb03968231c4ba722541198072b7e5203224f16a8c",
          "sha256": "e1655e834a71999acaef08bee2f9b11aebe8fd3612001a30c605c1d5041dc884",
          "sha1": "7db01d7a57865b2f4cc9c70c8e88be9ad024b4d4",
          "md5": "4dd2b2b78a5f10a732b2b293e685968a"
        }
      ]
    }
  ]
}
