{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosarm64-0.3.0-rc07.klib",
          "size": 202506,
          "sha512": "07b5bd97b47ea5722931227e8907440a41caf371fa02f7094b351dada95bd3904e85751a6d156225ab41fdbe2c8016e74d35abf5bae7beefd0873ea67e92fccb",
          "sha256": "ff21e4e6c6f1263f330d50da27d771845ae9910c409eb6775d24bc4801718f62",
          "sha1": "222221d6c496794832460a5b1af8334ee6e768e5",
          "md5": "bf90d93a77145482b6140461a6f4a881"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosarm64-0.3.0-rc07-metadata.jar",
          "url": "kmock-tvosarm64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "4320b3212c2d7700db5e688e5733a3f111d3f82dfb1fd22a5f834d97832857a3345d2932ccd67c37df5bdc076b6bf3eefc6f4c7745145b5904a3828cf92c3416",
          "sha256": "8567ee52de38fb5017f286552391efca5bbeb9dee7d905bd0aa7dc6866a514b5",
          "sha1": "915a1adc3c53f09ce5d5b8593ac06e76cdb43b36",
          "md5": "57b5704ac3e07e0e420bf71e408f21ae"
        }
      ]
    }
  ]
}
