{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-macosx64-0.3.0-rc05.klib",
          "size": 202549,
          "sha512": "2b4ff96681e0c8f762226453f9cdcd82635bc49384af516e7d3f787770f3cda1599c6a86e20eef25d952b3a73adc31cf1e000221d3cec482908e22d2aa71c109",
          "sha256": "99f65d8945d3dce1370e658031d5cd6ace06e15e8275c8dcb9808981beefa4b6",
          "sha1": "a71f0a76766a765c2a067a722ee68ee7e32b0755",
          "md5": "b69379c32ac93380862a8905514d904f"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-macosx64-0.3.0-rc05-metadata.jar",
          "url": "kmock-macosx64-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "4955064aa2fdf4243c1cd589ab1705ec77e6fa9bc6a2f8050b6215318e8d80573d36c976385c3ad24dff746b40f527a33dc17c49d67c9dc980475f9931fb5127",
          "sha256": "a857508fbdf47cfea2e4ecca870c88891ee761b9d1f6a90c275b286406c134b3",
          "sha1": "16f50460a990d188692c22783f4f3e938ec8c805",
          "md5": "81b979744577e4cca4d4d0911a929d60"
        }
      ]
    }
  ]
}
