{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx86-0.3.0-rc08.klib",
          "size": 203034,
          "sha512": "fcfb22e1fed7e27d2e8fe76a6ac7b88b6f1f91f3ea9da3cbf793c74ed6604b873b7eee29da428f1d540d6271a4b1b1cfbce55034f62e6d17b0d139ac7cf653f7",
          "sha256": "3c150aafd42291f27bb10329ca3afd6a0a9510837af193d76674a82e3b53c9ad",
          "sha1": "eebbb058f99da6c1d410831392040e6a51f06a7f",
          "md5": "47a3e75ba22177dce6d24b793df7a1bd"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx86-0.3.0-rc08-metadata.jar",
          "url": "kmock-watchosx86-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "1c3952a2da02f1f05ec8b1896b8b9909a44868d60505231fad86f9de0b40006f271f81cc22f67c67b157c9a1b28e29da330c8797332dc1996bd246cf1698db40",
          "sha256": "28a99ea7a794c30a935668fb705f05460d5ff3a35bbbd62ee9b273430e0d128a",
          "sha1": "81f4e0d220be5dd2f4817793718470bd0a5e62bf",
          "md5": "4f498622906008864db404632e46750b"
        }
      ]
    }
  ]
}
