{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01/kmock-0.3.0-rc01.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01.klib",
          "url": "kmock-js-0.3.0-rc01.klib",
          "size": 216790,
          "sha512": "7e5f129879fbac3fb3a2d8543008daaa967b8856282bcff56b9964aa0e874dc8729f84bb49a48383d3085816b581b5aaaf38957ce4bc419db9d3ff247d19a6bd",
          "sha256": "1e69567b30bab964c33644293e81daace1918a2f8e798918359525dd60a077b9",
          "sha1": "f239231f9a7e8267205f02df00410a32ffe83c61",
          "md5": "684aac0612f90fb1ff90375f8330dfe5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01.klib",
          "url": "kmock-js-0.3.0-rc01.klib",
          "size": 216790,
          "sha512": "7e5f129879fbac3fb3a2d8543008daaa967b8856282bcff56b9964aa0e874dc8729f84bb49a48383d3085816b581b5aaaf38957ce4bc419db9d3ff247d19a6bd",
          "sha256": "1e69567b30bab964c33644293e81daace1918a2f8e798918359525dd60a077b9",
          "sha1": "f239231f9a7e8267205f02df00410a32ffe83c61",
          "md5": "684aac0612f90fb1ff90375f8330dfe5"
        }
      ]
    }
  ]
}
