{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc06.klib",
          "size": 202480,
          "sha512": "0e523ce6e0b4a5ab72797274a3c33ed10bc8353c7099695b7a0ed0b4891fb4bbd2325705da9c045f7fa006c6ebbbb246ee8b1cccf05546e4fd01190529bfb645",
          "sha256": "57dea9b8ddbc177368e0555a671880b31b3db5da396ff6569a3f642383daf457",
          "sha1": "c9a6588d06ce5fc86435b1f900559e42cc1d4111",
          "md5": "532f91fd894e00421f5d24ff272d987e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc06-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "d6b3c977841b2d20a0cebe76333723aedbccedbca905e91a0b7ccbb8adbbe96053beba1d65e6ef839f7a2d3c29292d43fa75544da82c027f3c080e94776c39e3",
          "sha256": "52cfc63c35849931c0c7174eb566a1647a00048c3527820c6ff6a789dfb3bb43",
          "sha1": "4f35268105079cab326be958942e917b6a1ca1d0",
          "md5": "feab9260f4bae2d326d23d623a977593"
        }
      ]
    }
  ]
}
