{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-metadata-0.4.0-all.jar",
          "url": "ktx-datetime-0.4.0-all.jar",
          "size": 9008,
          "sha512": "85db2da3c9e30aa31377499b064be87183276e6d50f3f5b7d06b98f9940ebf5f7722ef60feff93d1be84914854268f9f7b8d82ad452e2a8521e7d04528ab4c71",
          "sha256": "30383e9f235dbcfa7c68adf7534a5e9f425e6a57de844c42dd4d34fa03ffd6da",
          "sha1": "2ec14c2a0bc157d29a795f3a4cbc876b7b0b9e73",
          "md5": "dc05654362813424be68a0d7ce9260eb"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktx-datetime-0.4.0.jar",
          "url": "ktx-datetime-0.4.0.jar",
          "size": 13895,
          "sha512": "8a758e9060a605c27a4fbac025eadb84e8c75295d13c0177e1475b4049be3558c9c2aa84f2d3375170b4c01d2e7555bbf91276e0a89aa7b3fa4d5c590e507db1",
          "sha256": "10a845c994dc34ec29aa736559e7708cdc4133cff15563b69bcb3dc7a89e5f89",
          "sha1": "f2d0c551e09159c456b7b1b21c359570a6600592",
          "md5": "752d2128a14c697040c010a73505949b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0/ktx-datetime-android-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0/ktx-datetime-android-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0/ktx-datetime-iosarm64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0/ktx-datetime-iosarm64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0/ktx-datetime-iossimulatorarm64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0/ktx-datetime-iossimulatorarm64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0/ktx-datetime-iosx64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0/ktx-datetime-iosx64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0/ktx-datetime-js-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0/ktx-datetime-js-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0/ktx-datetime-jvm-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0/ktx-datetime-jvm-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-linuxx64/0.4.0/ktx-datetime-linuxx64-0.4.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-linuxx64",
        "version": "0.4.0"
      }
    }
  ]
}
