{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx64-0.3.0-rc07.klib",
          "size": 202515,
          "sha512": "d21e9db6a8700ea1b5740963a9e4bc29a1f06b2e78765b491a96330c1e2064410c102eb18c7b5f765fea33ab48fc59c8fbde5f4da1fcd91c11ddb726adc5e2ac",
          "sha256": "cb2e1d675f1943e53e0ba1b69c52e3d7113463bf151bd9c9914e3ace847cc68a",
          "sha1": "23e96577ba5aca9df8ce17e9123b2261b9459e05",
          "md5": "eb978ade5f5c7b850d8674491f728a61"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx64-0.3.0-rc07-metadata.jar",
          "url": "kmock-watchosx64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "f0208840282917e69e7b25944cd2643f2ae5ba12f7918d81dcc1d626fa87e6df0b59184d7d2e2d1dbb06bdd6a570f1f31057fa78adc274b2fff10ffe9e7e3a63",
          "sha256": "dd7ec591e50087ad3e406ece6af6582d515f8698909918078f1a0f7f0afe08ea",
          "sha1": "2cb67f8e13bf4ac75f579de643d4d07002f6f3e9",
          "md5": "0d1be263f03b9a317edcee081e9525e3"
        }
      ]
    }
  ]
}
