{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04/kmock-0.3.0-rc04.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04.klib",
          "size": 202582,
          "sha512": "0926c1b9d60a4eff717d47f56dfaa941668d4b953a01beb174f9750da33bb25909b0b2e27922ff21ea04042dbea97a85ef75201bb848dfa2d865b364d07d70e1",
          "sha256": "54b3fe661c7f4b656ee43f6c787ff0ef6c6f22d39dcbcfa1a17f48ce5fd185e7",
          "sha1": "1a0f32ca28f8d3829b68cf78fbd24035882deaa3",
          "md5": "7a9ba0b9eea295703c7575febdf389f1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc04-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-metadata.jar",
          "size": 261,
          "sha512": "f87e6f1c84c7f17c4f439a5761efe3f0b470d035b3cfc95279fbcb0d7dd9c72a764d6dff79cc9d015bdae8ab0b908cccb1c4603b535b59c1db005567c28444aa",
          "sha256": "42be935de116c9cd4a1dc0570b849001144aa01004783c765c81a71a621cff01",
          "sha1": "63d1410fc918d833915f4769da8c03f4617c2c54",
          "md5": "6f190327be8206c684c82a478f7cafbe"
        }
      ]
    }
  ]
}
