{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0/core-0.4.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.4.0.klib",
          "size": 110285,
          "sha512": "57b10018447255354d0614bb1f51618d4b405b894bbb080e06b0be65e768ef002541654beaf439fa6ffbc3e5a56a2c62b92cc9416f5ac000a9dee06d0ed4ef63",
          "sha256": "8734c366a0a52cd463a7d7d805211f84ca1d92baf9feda5783617bc37e5821cc",
          "sha1": "26c4bbd246f0df0ee52df6a806315e9ee552b1c9",
          "md5": "72689d2ec45abda25026982db85a6489"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.4.0-metadata.jar",
          "url": "core-iossimulatorarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "01b2e3e638b3aa4791374db0822d8a37d61c61f95503d4e46f9bbcc827f464a08cf04eaff6e65fc94500112b0b91116cc3ad84f694f2a8b453d25c49f44ddcbb",
          "sha256": "99677aa96f84b3d93a7aa2ad2fdfb485a4e8a82f43d2f257e069b2d6f44dcacd",
          "sha1": "d2cfadd3896a3d9c5336d24d3be352921f57f1f0",
          "md5": "2b1bf94d4dad3dac6e2a81b5fb0a8551"
        }
      ]
    }
  ]
}
