{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.2.0-all.jar",
          "url": "core-0.2.0-all.jar",
          "size": 14820,
          "sha512": "850140b702403d81d5ed425592b9800d4b639f7617faccaca298f295b4789945d212c790f8b425cf383de0bfcdc7a80a2e4847adb54bd041995edd5c8f51a763",
          "sha256": "7fe56067a7e0d8110ca84e2c40aef366afcfab79ceba70c13ae787d4e2ebc55f",
          "sha1": "64a9dc8efb569538143d98754c98956a05bd12d3",
          "md5": "10048480520e4a094685145d1f7fb5e1"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-0.2.0.jar",
          "url": "core-0.2.0.jar",
          "size": 20370,
          "sha512": "6e056ce4321739fcb575908091b02706468ab40f870acd1f344d33401dba2907af54542699b51b8a3ebc0f299182389339134946f7f1a2e8a81810c066827fcf",
          "sha256": "80735c07dffa7f5c601940faeba668c810c179415bb461c11a9f230835ad46f0",
          "sha1": "24accf5a05f70413446ee370ffc2f54142e1d3d8",
          "md5": "8791ba6813780cb3fc6071769b3ba648"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.2.0/core-android-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.2.0/core-android-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.2.0/core-iosarm64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.2.0/core-iosarm64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.2.0/core-iossimulatorarm64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.2.0/core-iossimulatorarm64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.2.0/core-iosx64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.2.0/core-iosx64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.2.0/core-js-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.2.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.2.0/core-js-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.2.0/core-jvm-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.2.0/core-jvm-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.2.0/core-linuxx64-0.2.0.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "0.2.0"
      }
    }
  ]
}
