{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc03.jar",
          "url": "kmock-gradle-0.3.0-rc03.jar",
          "size": 75336,
          "sha512": "c76e8fb60909aa2e5acec5be09de0ee1d70a90c7aa1ca62c647eb7c5ae04238687908c07921b0e50ee6f29334b10047b1c037b6950913a250196e860688a9cf2",
          "sha256": "366b69270d08a67e03089720908c6540e9434b356532393b4e8af1f039ef3ff1",
          "sha1": "71d7e0745622a62ae46f5cb3c4cc0c750c634dbd",
          "md5": "9b2716c4220c39ce73a0b8ed766b2656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.7.0-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc03.jar",
          "url": "kmock-gradle-0.3.0-rc03.jar",
          "size": 75336,
          "sha512": "c76e8fb60909aa2e5acec5be09de0ee1d70a90c7aa1ca62c647eb7c5ae04238687908c07921b0e50ee6f29334b10047b1c037b6950913a250196e860688a9cf2",
          "sha256": "366b69270d08a67e03089720908c6540e9434b356532393b4e8af1f039ef3ff1",
          "sha1": "71d7e0745622a62ae46f5cb3c4cc0c750c634dbd",
          "md5": "9b2716c4220c39ce73a0b8ed766b2656"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc03-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc03-javadoc.jar",
          "size": 261,
          "sha512": "096e10ccc8d86dad8c899176567c83821c979b9414bb62806d0e417040673c0122af031f51cf1ebbc3f6fe5288dfd6d8aa3139dac907ea0c93c5ad455e88e8c0",
          "sha256": "08ac774347af43cbe00f83072ac4f56a66c9bf615f7a777854f51cbf230f988c",
          "sha1": "9abd3746973dc1f2b0b609633510e52e64c65692",
          "md5": "65ca35f024d795f81370e3efcfddad97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc03-sources.jar",
          "url": "kmock-gradle-0.3.0-rc03-sources.jar",
          "size": 15316,
          "sha512": "9cde54f9c381533d90ec0017926215b5bbe02b29e0bb40f4cf189da38dadc23ffd990069d6a11d5359ca1b4a202d7f98cbf91a50cf580fc2b7401b94f5b981b0",
          "sha256": "42eed86e09bd284b70c60029266b613fa4bc78619f105eab27274ef10c5b1123",
          "sha1": "284bd192437ac31c11afcc432bd95f6d22e0cbda",
          "md5": "2ce8911d11a3ce76c52227fd6e1c3459"
        }
      ]
    }
  ]
}
