{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1/core-0.3.1.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.1.klib",
          "size": 100062,
          "sha512": "af0e4ad91f1217859768632521c0e9ad494e0a763259bcdca9db9d63a55e6f572564a604efdb1496ce73cbb46d9e31ce8303f90089555ff053ece704e1914264",
          "sha256": "11ef00edd846c1b35748c20d88d969d7bd427b418b19ac1b234b734eca2648b1",
          "sha1": "d7a8516b83302aee111e62140d77fc49dd1c7243",
          "md5": "7a5c06aabb662bab856d62c9df04d38b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.1-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "e8d32af222c8442b9d9d263da327deb79739d1cf615f7e4b92d123aca75ae82aa2a100f3b23d6c6b36d616e2791609815416040503c23575fe999da74ebbf2cf",
          "sha256": "360a075476f56d2b1f472306d862221478c1767457a50eab60f1032987dd7ec7",
          "sha1": "b86b04bf05d42d5de5ab339f33fd8364419051f3",
          "md5": "41991fced55a7c1e3c4eb9ebb0e63c11"
        }
      ]
    }
  ]
}
