{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1/core-0.3.1.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.1.klib",
          "size": 100062,
          "sha512": "af0e4ad91f1217859768632521c0e9ad494e0a763259bcdca9db9d63a55e6f572564a604efdb1496ce73cbb46d9e31ce8303f90089555ff053ece704e1914264",
          "sha256": "11ef00edd846c1b35748c20d88d969d7bd427b418b19ac1b234b734eca2648b1",
          "sha1": "d7a8516b83302aee111e62140d77fc49dd1c7243",
          "md5": "7a5c06aabb662bab856d62c9df04d38b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.1-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "68e9533dba69e44e1ec303fa559d0b89d19810c0e23c55454c30564be56d93e5aa82578d0ca1cdb9a7799f31cdd77243616f4c48fd5f0cf30b58cbfe750a7a90",
          "sha256": "76f66dc9cb76525a450edb8a0911f341d5a487368b82ef78c78693932aae09c1",
          "sha1": "f4b22bb96783349de4c51b587550ebd37c9498f0",
          "md5": "7076805d03b660ecbbb602ad5cd576ad"
        }
      ]
    }
  ]
}
