{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvossimulatorarm64-0.3.0-rc06.klib",
          "size": 202591,
          "sha512": "69208552e565f735f39e7da1108b70d7226d0f7c0ee2e7e58f965bcc0fa889157dfeb0cf8993c9c5d1d7cbc4a4d126408214c82cd96828d994b08efd16375236",
          "sha256": "2f3e1b2f8e0211a67819b60c279702b116367b293116b5440909b59ad7df370e",
          "sha1": "f8be3fe63d7a689e35366437ea5bac0435f54680",
          "md5": "3ff5eb6bcc766a155ed7669227b130b4"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvossimulatorarm64-0.3.0-rc06-metadata.jar",
          "url": "kmock-tvossimulatorarm64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "3e96288124640a69458db019eed5c6d68a16accc1dcab22c8972cca9293e0a8b9f9e3b70603f4a15e34e3bc786db1e3ecd383484546dd5488071a57fc7a15f81",
          "sha256": "baa63c646a475ed88f560679a21dd699d42fe573ac67fb2e3c0f15cbb5111904",
          "sha1": "9117c4c98aedfed42bc54aef5434a2c1064dec22",
          "md5": "a66232f32f5e2816bd7a42fe1af165dc"
        }
      ]
    }
  ]
}
