{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc06.klib",
          "size": 202582,
          "sha512": "5a29bb4688f1136d451406b2eefd19dd88123a737d4b27c4b9dbc3fbc4d09d9eefe0ce490a7e34af9b7109055d56a2fdc6b0c8e969b3733e2d8454aa2a52ba91",
          "sha256": "78d3245c443c5470f125a9a92363f50bdb45a1e28eafbde12141b30d49c8cc27",
          "sha1": "b39735cd4c103ca6e73b0f70f494f56b518983ff",
          "md5": "6ff1309eaa9ad9f7e525950fc0334b4d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc06-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "7c5cb95688545cdb131c10a648d6f58ddd677064203d87e43d5d03308a5322cf419b2511d2ca958a75d20e6d2ba02b4a2555709bf32b746d8f98ac2ae2973cc2",
          "sha256": "6c45c47027fb7ed285bedd4b98be3f77e90670b24671891d25eea4087f72bd67",
          "sha1": "1c826acb7a6efb90917d3b78bf87ad27b270db51",
          "md5": "a7f31dfd5543f303c79869faaab8eee5"
        }
      ]
    }
  ]
}
