{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc08/kmock-0.3.0-rc08.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc08.klib",
          "size": 202997,
          "sha512": "1b888bc9c32633c3e99493ac516a0a56e988bcadad09e2d01738d059792b2dc4baf3e2e2bd3a47093e4f8b372580a2138b883c6711c370f9c377f744e679f57b",
          "sha256": "aa97495db8f57ec897a3ef95aa008ed4bc3e886e153afb8416096ca572fd7d6a",
          "sha1": "d01e1a4cd7ba745144446b06ea225f474dc15ee2",
          "md5": "f858e0d575ca9be6407e40db61c2f03b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc08-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc08-metadata.jar",
          "size": 261,
          "sha512": "5cef21486ff1ee621867191b4ebfb667998a58ad457c8e463d5f2f221a46bf27eefe82b04f11d083787b475d71c93e5de426a9d15b1ccd2e9fde836892e29f42",
          "sha256": "e34157d0ee65cdd1144a4402fb443163ee8b8f6c1945d55f7fe93d517c7fcd24",
          "sha1": "20732c8b043d21a5e44771e96751cee2031d8f1c",
          "md5": "f5a17e037835e343ce7edef662687172"
        }
      ]
    }
  ]
}
