{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03/kmock-0.3.0-rc03.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc03.klib",
          "size": 202580,
          "sha512": "45997cf8fc1c9c07753c2ed18e90621c27a7f585b538da1d34aaaba0ac0d770772b135a59fe6b337daf8afd3dd4bec0849718a4a6dae9ef137035edae788e28a",
          "sha256": "361d5eee4b94d0d1032791e890dcdf49b6feae166ebc24fe191e5f2de3211fef",
          "sha1": "9bb1279019b5ecc0acc9744430889ee4924394de",
          "md5": "e22b9ae6b7eb656f2d8b9a3139310b8d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc03-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc03-metadata.jar",
          "size": 261,
          "sha512": "ec883ec07beb2ac9aba47232afce3738b591735b32dc8a3170edbc7b37d598865bdf3f33fe348888401847e0fe4511d750e2216f3699200aab02acb58c17e4f3",
          "sha256": "5c9750c1537e72c83c2e881a0b3f57a3cd11ee50f2054601b9997223d2daa4f5",
          "sha1": "85ecf76eedcc228225ea9c39e7ba9fad51a8af99",
          "md5": "ee86a2dca4e2f371c77b6f54c786567b"
        }
      ]
    }
  ]
}
