{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03/kmock-0.3.0-rc03.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc03.klib",
          "size": 202478,
          "sha512": "d7ae43050a139002a22e8329c426a9535b320f2d89107147fffc64398c5312501f5d1d3ec36ab2b48b1ca0b476806e70352c17221a276721bc6660ad80f0fa6e",
          "sha256": "f38ec759a1cb6eb75d0554d353cc7256e68c2aaf9f3ef3eb1196c3fd28cd9f21",
          "sha1": "09eefe70f3fcedf3ed7e20bbc08efbd627b263db",
          "md5": "170fedad2da8dc8de87c0ab695a63741"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc03-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc03-metadata.jar",
          "size": 261,
          "sha512": "ec883ec07beb2ac9aba47232afce3738b591735b32dc8a3170edbc7b37d598865bdf3f33fe348888401847e0fe4511d750e2216f3699200aab02acb58c17e4f3",
          "sha256": "5c9750c1537e72c83c2e881a0b3f57a3cd11ee50f2054601b9997223d2daa4f5",
          "sha1": "85ecf76eedcc228225ea9c39e7ba9fad51a8af99",
          "md5": "ee86a2dca4e2f371c77b6f54c786567b"
        }
      ]
    }
  ]
}
