{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosarm32-0.3.0-rc06.klib",
          "size": 202531,
          "sha512": "41774b89030faa630e4f318c7ab2913e8e6c1e169c993d1a379f19a01c660797f9e382d9a7026e001545526fce8a1267da7ed197b093355dbcbbe0116119e249",
          "sha256": "58e2d89168258b33fc8fa3b34e9a8c43f81f454cf6c5df0a442b121425ca4584",
          "sha1": "40c861cddc6d66a3af24a5866c681b98ef35cd37",
          "md5": "3979a5ed96ce615235f78e5e9c01177e"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosarm32-0.3.0-rc06-metadata.jar",
          "url": "kmock-watchosarm32-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "01b33403fff679808e384f9c12ca1136320d651ca5d292b5f241e1dd5f2dea155549e547715627f5d2956a71927883483ecac59513fca76f517790d5362d35c0",
          "sha256": "9a6111a0c9e53cbc2864375d8606a4cda801d18cbeae89644cb85fc51b247349",
          "sha1": "cc5a29f5e991752eabbd881782340c16db6c6273",
          "md5": "c3865f655b18a0c543f8085080170b97"
        }
      ]
    }
  ]
}
