{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosarm32-0.3.0-rc05.klib",
          "size": 202531,
          "sha512": "3984e0424a5ff970760840f4e11b52700d5d629d30422b8e8a3bbd188a864fd6994ce89d59590cb145476e9d621bc4b6414d300b7d78c39180bd25ac4459efe8",
          "sha256": "5243093da319ad2071e0c31c35c802f5b1d2d76aa904bda9e4654c2e69f6a27e",
          "sha1": "6d7acdb4f709600c889c9abf2151d56891348c4b",
          "md5": "8fa983fc34830b5b49bd76f75a4a0303"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosarm32-0.3.0-rc05-metadata.jar",
          "url": "kmock-watchosarm32-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "0f517dd69eddaecbab6afd1d4ca92f54ad3d27bb8c4585ff1efccfc836143d014dec2453c79ec1616732f29e6029fdd385fd9f0dd0e55fd383586c1a2294e623",
          "sha256": "2f80156fee05ca944eca5e848c4028f86a45abe581fc25a04ce7d909ace461aa",
          "sha1": "d60b5415893f5f006a70284b7dd6069afca91472",
          "md5": "6f0178cbcb5442c5f620a84a6ddadd01"
        }
      ]
    }
  ]
}
