{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0/core-0.1.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.1.0.klib",
          "url": "core-js-0.1.0.klib",
          "size": 61528,
          "sha512": "ae4c787fc9534b00119b41c8c122d0fb5cffbe247659fad966f859601dbbcdbf49d23b5d05d1d75888b44a51caff4beaf5f536e811c7ddeaaf8fadd623bba7a8",
          "sha256": "3898cf2890137eec5b2ed4e6aa32b8650a728324cf5c6faeab1b9213aa320d7f",
          "sha1": "56b44f3e9c8bc80b5f625b3a6e106894e61079e1",
          "md5": "7ef7e9f43b2c95764905dd5eb8e70a1c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.1.0.klib",
          "url": "core-js-0.1.0.klib",
          "size": 61528,
          "sha512": "ae4c787fc9534b00119b41c8c122d0fb5cffbe247659fad966f859601dbbcdbf49d23b5d05d1d75888b44a51caff4beaf5f536e811c7ddeaaf8fadd623bba7a8",
          "sha256": "3898cf2890137eec5b2ed4e6aa32b8650a728324cf5c6faeab1b9213aa320d7f",
          "sha1": "56b44f3e9c8bc80b5f625b3a6e106894e61079e1",
          "md5": "7ef7e9f43b2c95764905dd5eb8e70a1c"
        }
      ]
    }
  ]
}
