{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc06/kmock-0.3.0-rc06.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx64-0.3.0-rc06.klib",
          "size": 202515,
          "sha512": "57b724018d1427c83417ab27ef2283f952563e76f83801a4421b8d524131a2afcd136873c701cf41b1890af89589f7d45d4235b53a17732ef7232b4ab3d791d6",
          "sha256": "7c82bcc0a691c5dcd8fe419d28b5fb41a40084727c91ad50ddbced435263a5ed",
          "sha1": "bef6d709a39501dc0c975d42e396fc5dc2ad3fb7",
          "md5": "9ac8f15cea9c211a11d7fd7c3425cfdf"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx64-0.3.0-rc06-metadata.jar",
          "url": "kmock-watchosx64-0.3.0-rc06-metadata.jar",
          "size": 261,
          "sha512": "2e211be25963b7b7d52b1271bd59fd7a82d436461f6bf64b246e4384bb3afba61fa798ecedfcb69e290072f1fb4579ed3447837653bc744d32c5ebc83c6da208",
          "sha256": "264bdf7dc9f6954e0b4bd49579c3cb3503c269a62deb873df18350e45dddb78f",
          "sha1": "02dd0bd47b8405bc0fc282d2c9610e5062b643d3",
          "md5": "cf209f77bd0ed6b253db5c7792325226"
        }
      ]
    }
  ]
}
