{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0/core-0.4.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0.klib",
          "url": "core-js-0.4.0.klib",
          "size": 134545,
          "sha512": "7a773f599353e27d45de578582382d57749b1486894be57cbcbb11ac32289433380dc920ba9a26bd6b7ac700b396179b7f0f483db45bbf9040ccf94b785fb43f",
          "sha256": "bafd92334cecc769e01451bc96fdef5b488a15566c4cadf32d719c3894825a6a",
          "sha1": "97e3090498d9f67528c2e7702e866612a4a49d4a",
          "md5": "2ce057cae06a3ba606f4beeaa0211247"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0.klib",
          "url": "core-js-0.4.0.klib",
          "size": 134545,
          "sha512": "7a773f599353e27d45de578582382d57749b1486894be57cbcbb11ac32289433380dc920ba9a26bd6b7ac700b396179b7f0f483db45bbf9040ccf94b785fb43f",
          "sha256": "bafd92334cecc769e01451bc96fdef5b488a15566c4cadf32d719c3894825a6a",
          "sha1": "97e3090498d9f67528c2e7702e866612a4a49d4a",
          "md5": "2ce057cae06a3ba606f4beeaa0211247"
        }
      ]
    }
  ]
}
