{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07/kmock-0.3.0-rc07.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-macosarm64-0.3.0-rc07.klib",
          "size": 202566,
          "sha512": "b4d53bceb97095886ccacdc8ae5a10b6b4c9499167150e05d06262df5222ca09f737938c728b0862aa75e776f7450041135c8c35d582bc42abb49ea51b72649e",
          "sha256": "797ef072db0cfaec9551f6ea2004a0221c11aaefc8f76d7b642651e61539a31d",
          "sha1": "8cd69cf1424d6fef3843ddfa32f404ab4264625f",
          "md5": "75c850a50a2398d6292234dbb0f622f6"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-macosarm64-0.3.0-rc07-metadata.jar",
          "url": "kmock-macosarm64-0.3.0-rc07-metadata.jar",
          "size": 261,
          "sha512": "d552c70f95b55cf52e45025be9428a47ccc28360a7208d1948cb3d8e406749296501866a79bfe086758b6dc4f912078e7454fc0a0488473d91efc817f23dfdfe",
          "sha256": "6599f9285a5f716e7e20d7db36cb87a9ee1f96461aae710d5199508472c8cb20",
          "sha1": "a28ca89bfc91cf679c1fbd1e9a8fe474945605ac",
          "md5": "ceb2b5709f364fb3167ee1563e853609"
        }
      ]
    }
  ]
}
