{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0/core-0.1.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.1.0.klib",
          "size": 50782,
          "sha512": "7ddb4ee98243589851f71d33e084cc52c26d1ae5983f6125a80363e5eef71b9cc4f8329110beb5baf6129d38c4d01fe7e224588703daa3ef943b2240f5f11104",
          "sha256": "c016d48e9d100fadca3d144287a666437f7dc9aa9ef8d09649d59bd5b4d2b79f",
          "sha1": "a5880dca2a70923ee57c0caef5ad65c9ebdfcf34",
          "md5": "99bc61466b7c03ae723cc3aee13b48c8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "core-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "c5ec22bc11ff5ef97ead79d5f324de9ef6b97595486e5170d48c96fa645f8eb58f551b3a2d5b58e8d88b220968ad8afbfb5df3845cc9dc5857f1648fe389a084",
          "sha256": "4faad09a750130e36b22fb722c53de781fa9a3bea118353ad53161b78b4453b9",
          "sha1": "1751953a6c6f4c3297fe11a63d7b043fed86eb6c",
          "md5": "34a937e5d6bd039625333bf033bf694e"
        }
      ]
    }
  ]
}
