{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05/kmock-0.3.0-rc05.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-tvosx64-0.3.0-rc05.klib",
          "size": 202489,
          "sha512": "f299869102c96888403878f57057a93ab96af49ae2e67e4871bc79fe217f6381d16604c8403c9d21338d2041d08bde6ba261c8078d9f6ce07a6fb5a2d48a9c29",
          "sha256": "5d6b4ad3944023740640ab61448c985111853c5c2284775bf0386da3e4de2a50",
          "sha1": "1061ccebb5c010f28d5f3c0bc0bbfa7aea8368fc",
          "md5": "75862a59671517e0945516ac70808760"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-tvosx64-0.3.0-rc05-metadata.jar",
          "url": "kmock-tvosx64-0.3.0-rc05-metadata.jar",
          "size": 261,
          "sha512": "b62c696b2a92e56f1431645be76d98ca9a6e3933f2b1c96687a85766f63e118f5d773c7b98f39c07ca2bfd4d77993f7d09ec457905e5ac797b033113bc1bbe0f",
          "sha256": "e951ce63bffd41a9dd06cd378971c6ad6a97f38a7fb3c283489c2bc2176a6347",
          "sha1": "35c0eb6ecbf08575e6fb5b5579c17bc578cb616e",
          "md5": "fffceff2b9164c54c680f28121764e35"
        }
      ]
    }
  ]
}
