{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1.jar",
          "url": "kmock-gradle-0.1.1.jar",
          "size": 33056,
          "sha512": "5d2e8a814405cdeb73c0fa9b00f27840db055c64fc02b51522be20fab68c3733799922358ab40252121907c6455e5076edbd04c6b0aa32f0b805b5e227874745",
          "sha256": "3c1ff93118e9ee65d2ce26fde9708a5cf93030adbdddaf5a39dde7876d074b53",
          "sha1": "df0251d11946768d6109ac627ea72d9dc34e770f",
          "md5": "477ec895f66cf398db537ddb2cdb28b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1.jar",
          "url": "kmock-gradle-0.1.1.jar",
          "size": 33056,
          "sha512": "5d2e8a814405cdeb73c0fa9b00f27840db055c64fc02b51522be20fab68c3733799922358ab40252121907c6455e5076edbd04c6b0aa32f0b805b5e227874745",
          "sha256": "3c1ff93118e9ee65d2ce26fde9708a5cf93030adbdddaf5a39dde7876d074b53",
          "sha1": "df0251d11946768d6109ac627ea72d9dc34e770f",
          "md5": "477ec895f66cf398db537ddb2cdb28b0"
        }
      ]
    }
  ]
}
