{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.0/core-0.3.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.3.0.klib",
          "size": 99985,
          "sha512": "0c301db62a0d9b0cf59d5623b97c0ded592cceeb746e103afdb74a670d012210a99a9cef09b2f5649172e59b451c0bf49fe144b8d8d0e87c3c0b3c63983a7162",
          "sha256": "3449472ab09ce1069a26cefdc95cd9449834d8afb021c6458800a1be9e843453",
          "sha1": "d7aa118a7f8888a6db844a5a8a1011d4acac77a2",
          "md5": "423ce540dea342b500495ee66569574a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.3.0-metadata.jar",
          "url": "core-iosarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "85aaf918801d733f64877c87aeb58cd0cb20d9ff4caed1b37e494e92c5b45343cbb995bc2c649415d8d3164dfd2d88dd4fdf85ffd9fc016d33ae90d593cb00ea",
          "sha256": "b66b7e6799b82be9bab1296f8165d148fd59f4130c94c97c120328506b29105b",
          "sha1": "50c053ed827de507434a657db67c517d1e8da0ea",
          "md5": "46996d7f4f9bc09d6a4ab1fd82867918"
        }
      ]
    }
  ]
}
