{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0/core-0.4.0.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.4.0.klib",
          "size": 110198,
          "sha512": "73826a3e4475fea307e487074fbe1f069ad0d001c87e48d2d2ecf2bb3cb2399efcb2e35964ee78be1b0ea65d3145273fcb26b9d7a0cff2c6bc6f6a9082e179b5",
          "sha256": "c56da9bb532caf18e1d71687bfdf8b5207a97a716befe0b589092605992580fc",
          "sha1": "25789a733c44b1d763db79f108203694980f1f5c",
          "md5": "2aabc1b5ef9e65eb15ed392f2abca7ec"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.4.0-metadata.jar",
          "url": "core-iosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "01b2e3e638b3aa4791374db0822d8a37d61c61f95503d4e46f9bbcc827f464a08cf04eaff6e65fc94500112b0b91116cc3ad84f694f2a8b453d25c49f44ddcbb",
          "sha256": "99677aa96f84b3d93a7aa2ad2fdfb485a4e8a82f43d2f257e069b2d6f44dcacd",
          "sha1": "d2cfadd3896a3d9c5336d24d3be352921f57f1f0",
          "md5": "2b1bf94d4dad3dac6e2a81b5fb0a8551"
        }
      ]
    }
  ]
}
